# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: LONG team
# Description of the Site
description: development of a free cryptocurrency
# URL of Image of the Site
site-image: /assets/images/crypton2.jpg
# Keywords of the Site
site-keywords: blockchain, network, coin,  social, cryptocurrency, long coin, wlong
# URL for the Image of custom Favicon
favicon-url: /assets/images/long128x128.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
#heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: /assets/images/crypton2.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: steephairy@gmail.com
#facebook_username: thedevslot
#twitter_username: thedevslot
#instagram_username: thedevslot
#linkedin_username: thedevslot
telegram_username: longteam
telegram_news: longteamnews
github_username: longnetwork
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /


# Google Analytics
#google-analytics: UA-163806439-1

# Disqus
#disqus-shortname: thedevslot

# Name of the Author
author-name: LONG team
# URL for the Image of the Author
author-image: /assets/images/long128x128.png
# 60 Words About the Author
author-about: If a community within a house, street, district, city, country, continent, planet agrees to consider something as money, then it becomes money within the house, street, district, city, country, continent, planet, and nothing more is required. ©longteam
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/longnetwork

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
